openapi: 3.0.0
info:
  title: Server API List
  description: This is a reference api list of Backend.
  version: 1.0.0
  contact:
    email: ankuragarwa246@gmail.com
servers:
  - url: http://localhost:9999/api
    description: Development server
  - url: 
    description: Production Server
paths:
  /question/getAll:
    get:
      tags:
        - Question
      summary: Get all questions
      parameters:
        - in: query
          name: page
          description: Page Number
        - in: query
          name: limit
          description: Limit of questions per page
        - in: query
          name: sort
          description: Sort by difficulty or marks
      responses:
        '200':
          description: Questions Fetched Successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /question/create:
    post:
      tags:
        - Question
      summary: Create a Question
      requestBody:
        $ref: '#/components/requestBodies/CreateUpdateQuestion'
      responses:
        '200':
          description: Question Created Successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /question/update/{questionId}:
    put:
      tags:
        - Question
      summary: Update a Question
      parameters:
        - in: path
          name: questionId
          description: Question ID
          schema:
            type: string
            format: ObjectId
      requestBody:
        $ref: '#/components/requestBodies/CreateUpdateQuestion'
      responses:
        '200':
          description: Question Updated Successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /question/get/{questionId}:
    get:
      tags:
        - Question
      summary: Get a Question
      parameters:
        - in: path
          name: questionId
          description: Question ID
          schema:
            type: string
            format: ObjectId
      responses:
        '200':
          description: Question Fetched Successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /question/delete/{questionId}:
    delete:
      tags:
        - Question
      summary: Delete a Question
      parameters:
        - in: path
          name: questionId
          description: Question ID
          schema:
            type: string
            format: ObjectId
      responses:
        '200':
          description: Question Deleted Successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Errors
  /question/searchByDifficulty:
    post:
      tags:
        - Question
      summary: Search questions based on difficulty.
      requestBody:
        $ref: '#/components/requestBodies/SearchByDifficulty'
      responses:
        '200':
          description: Questions Fetched Successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /question/searchBySubject:
    post:
      tags:
        - Question
      summary: Search questions based on subject.
      requestBody:
        $ref: '#/components/requestBodies/SearchBySubject'
      responses:
        '200':
          description: Questions Fetched Successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
components:
  schemas:
    Question:
      type: object
      properties:
        id:
          type: string
        question:
          type: string
        subject:
          type: string
        topic:
          type: string
        difficulty:
          type: string
        marks:
          type: string
        creationDate:
          type: string
          format: date-time
    CreateUpdateQuestionInput:
      type: object
      properties:
        question:
          type: string
        subject:
          type: string
        topic:
          type: string
        difficulty:
          type: string
        marks:
          type: string
  requestBodies:
    CreateUpdateQuestion:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateUpdateQuestionInput'
        description: Create/Update Question
    SearchByDifficulty:
      content:
        application/json:
          schema:
            type: object
            properties:
              difficulty:
                type: string
            description: Search by difficulty
    SearchBySubject:
      content:
        application/json:
          schema:
            type: object
            properties:
              subject:
                type: string
            description: Search by subject