openapi: 3.0.0
info:
  title: Server API List
  description: This is a reference api list of Backend.
  version: 1.0.0
  contact:
    email: ankuragarwa246@gmail.com
servers:
  - url: http://localhost:9999/api
    description: Development server
  - url: 
    description: Production Server
paths:
  /questions:
    get:
      tags:
        - Common
      summary: Get all questions
      parameters:
        - in: query
          name: page
          description: Page Number
        - in: query
          name: limit
          description: Limit of questions per page
        - in: query
          name: sort
          description: Sort by popular (default) or recent
      responses:
        '200':
          description: Questions Fetched Successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /fetchQuestion/{questionId}:
    get:
      tags:
        - Common
      summary: Get a Question
      parameters:
        - in: path
          name: questionId
          description: Question ID
          schema:
            type: string
            format: ObjectId
      responses:
        '200':
          description: Question Fetched Successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
components:
  schemas:
    Question:
      type: object
      properties:
        id:
          type: string
        question:
          type: string
        subject:
          type: string
        topic:
          type: string
        difficulty:
          type: string
        marks:
          type: string
        creationDate:
          type: string
          format: date-time
    CreateQuestionInput:
      type: object
      properties:
        question:
          type: string
        subject:
          type: string
        topic:
          type: string
        difficulty:
          type: string
        marks:
          type: string
    UpdateQuestionInput:
      type: object
      properties:
        question:
          type: string
        subject:
          type: string
        topic:
          type: string
        difficulty:
          type: string
        marks:
          type: string
  requestBodies:
    CreateQuestion:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateQuestionInput'
        description: Create Question
    UpdateQuestion:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateQuestionInput'
        description: Update Question